# Generated by Django 3.2.16 on 2025-05-18 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_used',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.promocode'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='code_type',
            field=models.CharField(choices=[('daily', 'Ежедневный'), ('first_order', 'На первый заказ'), ('custom', 'Пользовательский')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['user', 'code_type', 'is_active'], name='food_promoc_user_id_302912_idx'),
        ),
    ]
