# Generated by Django 3.2.16 on 2025-05-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20250518_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в обработке', 'В обработке'), ('подтвержден', 'Подтвержден'), ('в пути', 'В пути'), ('доставлен', 'Доставлен'), ('отменен', 'Отменен')], default='в обработке', max_length=20),
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
