# Generated by Django 3.2.16 on 2025-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20250518_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в обработке', 'В обработке'), ('подтвержден', 'Подтвержден'), ('в пути', 'В пути'), ('доставлен', 'Доставлен'), ('отменен', 'Отменен')], default='pending', max_length=20),
        ),
    ]
