# Generated by Django 3.2.16 on 2025-05-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
